//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrnekProje.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OrnekProjeEntities : DbContext
    {
        public OrnekProjeEntities()
            : base("name=OrnekProjeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dersler> Dersler { get; set; }
        public virtual DbSet<Sayfalar> Sayfalar { get; set; }
        public virtual DbSet<SinavHaftasi> SinavHaftasi { get; set; }
        public virtual DbSet<Siniflar> Siniflar { get; set; }
        public virtual DbSet<Sinavlar> Sinavlar { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
    
        public virtual ObjectResult<spMenuList_Result> spMenuList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spMenuList_Result>("spMenuList");
        }
    }
}
