//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrnekProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sinavlar
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> SınavTarihi { get; set; }
        public Nullable<int> SınavHaftasiId { get; set; }
        public Nullable<int> DersId { get; set; }
        public Nullable<int> SinifId { get; set; }
        public Nullable<int> Saat { get; set; }
        public Nullable<System.DateTime> OTarih { get; set; }
    }
}
